"""Export the best ASC-only calibration eval to a YAML file.

Reads optimization_asc_only.p (boptx pickle), finds the evaluation with the
lowest objective value, and writes calibrated_asc.yml with the ASC values
plus a provenance header.

Tie-breaker: if multiple evals are within --tolerance (default 0.001) of the
global minimum objective, pick the one with the smallest sum of absolute ASC
values. This prefers parsimony: when several parameter sets fit the data
equally well, we choose the closest-to-default one.

Handles both 4-param (car/bike/walk/pt) and 5-param (+ carPassenger) runs:
the parameter set is inferred from the length of the eval's values array.

Usage:
    cd matsim_scenarios/bavaria/calibration/boptx
    python export_calibrated_asc.py [--tolerance 0.001]
"""
import argparse
import datetime as dt
import os
import pickle


PARAM_NAMES_4 = ["car.alpha_u", "bike.alpha_u", "walk.alpha_u", "pt.alpha_u"]
PARAM_NAMES_5 = PARAM_NAMES_4 + ["carPassenger.alpha_u"]


def _extract(ev, key):
    """Extract a field from an eval that may be a dict or an Evaluation object."""
    if isinstance(ev, dict):
        return ev.get(key)
    # Evaluation object with get_* accessors
    getter = getattr(ev, f"get_{key}", None)
    return getter() if getter else None


def find_best(pickle_path, tolerance=0.001):
    with open(pickle_path, "rb") as f:
        data = pickle.load(f)

    candidates = []
    if isinstance(data, dict):
        for key in ("evaluations", "finished", "history"):
            if key in data:
                candidates.extend(data[key])
    elif isinstance(data, list):
        candidates = data
    else:
        for attr in ("evaluations", "finished", "history"):
            if hasattr(data, attr):
                candidates.extend(getattr(data, attr))

    if not candidates:
        raise SystemExit(f"No evaluations found in {pickle_path}")

    # Collect all non-transitional evals with readable objectives
    evals = []
    for ev in candidates:
        obj = _extract(ev, "objective")
        if obj is None:
            continue
        if _extract(ev, "transitional"):
            continue
        vals = _extract(ev, "values")
        if vals is None:
            continue
        evals.append((obj, ev, vals))

    if not evals:
        raise SystemExit("No evaluation had a readable objective")

    global_min_obj = min(o for o, _, _ in evals)

    # Candidates within tolerance of the global minimum
    near_best = [(o, ev, vals) for o, ev, vals in evals if o <= global_min_obj + tolerance]

    # Tie-break: pick the one with smallest sum of |ASC| values
    near_best.sort(key=lambda t: (sum(abs(v) for v in t[2]), t[0]))
    obj, best_ev, vals = near_best[0]

    print(f"Best objective:         {global_min_obj:.6f}")
    print(f"Chose within tolerance {tolerance:.4f}: obj={obj:.6f}")
    print(f"  |ASC| sum = {sum(abs(v) for v in vals):.4f}")
    print(f"  candidates in tolerance band: {len(near_best)}")

    return obj, best_ev, vals


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pickle", default="optimization_asc_only.p")
    ap.add_argument("--output", default="calibrated_asc.yml")
    ap.add_argument("--tolerance", type=float, default=0.001,
                    help="Within tolerance of best obj, prefer smallest |ASC| sum")
    args = ap.parse_args()

    pickle_path = os.path.abspath(args.pickle)
    output_path = os.path.abspath(args.output)

    obj, ev, values = find_best(pickle_path, tolerance=args.tolerance)
    if len(values) == 4:
        param_names = PARAM_NAMES_4
    elif len(values) == 5:
        param_names = PARAM_NAMES_5
    else:
        raise SystemExit(f"Unexpected number of parameters: {len(values)}")

    today = dt.date.today().isoformat()
    lines = [
        "# calibrated_asc.yml - generated by export_calibrated_asc.py",
        f"# Source pickle: {pickle_path}",
        f"# Best objective (L1 over 20 distance bins x 5 modes): {obj:.6f}",
        f"# Calibration target: MiD 2017 Niederbayern",
        f"#   (reference_trips.csv verified vs PDF Abbildung 22)",
        f"# Tie-break tolerance: {args.tolerance}",
        f"# Generated: {today}",
        "",
    ]
    for name, val in zip(param_names, values):
        lines.append(f"{name}: {float(val):+.6f}")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {output_path}")
    print(f"  objective = {obj:.6f}")
    for name, val in zip(param_names, values):
        print(f"  {name:20s} = {float(val):+.6f}")


if __name__ == "__main__":
    main()
